apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      volumes:
      - name: redpanda-storage
        hostPath:
          path: /var/lib/redpanda
      containers:
      - image: docker.redpanda.com/vectorized/redpanda:latest
        imagePullPolicy: IfNotPresent
        command: ["redpanda"]
        args: [
          "start",
          "--overprovisioned",
          "--smp",
          "1",
          "--memory",
          "1G",
          "--reserve-memory",
          "0M",
        ]
        name: single-minio
        ports:
        - containerPort: 8081
        - containerPort: 8082
        - containerPort: 9092
        - containerPort: 9644
        volumeMounts:
        - mountPath: "/var/lib/redpanda/data"
          name: redpanda-storage
