apiVersion: v1
kind: PersistentVolume
metadata:
  name: single-minio-pv-volume2
  labels:
    type: local
spec:
  storageClassName: manual
  volumeMode: Block
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/single_minio_pv.data"
  persistentVolumeReclaimPolicy: Delete
