apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: single-minio-pv-claim
spec:
  volumeMode: Block
  # storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
